CREATE TABLE SUPPLIER (
  ID INTEGER  NOT NULL    ,
  NAME VARCHAR(256)  NOT NULL  ,
  SHIPPING_DAYS INTEGER  NOT NULL    ,
PRIMARY KEY(ID));

CREATE TABLE PRODUCT (
  ID INTEGER  NOT NULL    ,
  CODE VARCHAR(32)  NOT NULL    ,
  IMAGE BLOB   ,
PRIMARY KEY(ID)  );

CREATE TABLE MARKET_USER (
  ID INTEGER  NOT NULL    ,
  MAIL VARCHAR(100)  NOT NULL  ,
  PASSWORD VARCHAR(256)  NOT NULL  ,
  NAME VARCHAR(50)  NOT NULL  ,
  SURNAME VARCHAR(50)  NOT NULL  ,
  LANGUAGE CHAR(2)  NOT NULL    ,
PRIMARY KEY(ID)  );

CREATE TABLE DISCOUNT (
  ID INTEGER  NOT NULL    ,
  SUPPLIER_ID INTEGER  NOT NULL  ,
  DATE_FROM DATE  NOT NULL  ,
  DATE_TO DATE  NOT NULL  ,
  PRICE_RANGE_FROM NUMERIC(10,2)    ,
  PRICE_RANGE_TO NUMERIC(10,2)    ,
  MIN_PIECE_DISCOUNT INTEGER      ,
  PERCENTAGE NUMERIC(5,2)      ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIER(ID));


CREATE TABLE PRODUCT_DICTIONARY (
  ID INTEGER  NOT NULL    ,
  PRODUCT_ID INTEGER  NOT NULL  ,
  NAME VARCHAR(256)  NOT NULL  ,
  DESCRIPTION VARCHAR(2048)    ,
  LANGUAGE CHAR(2)  NOT NULL    ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCT(ID));

CREATE TABLE PRODUCT_SUPPLIER (
  PRODUCT_ID INTEGER  NOT NULL  ,
  SUPPLIER_ID INTEGER  NOT NULL  ,
  PRICE NUMERIC(10,2)  NOT NULL  ,
  AVAILABILITY INTEGER  NOT NULL    ,
PRIMARY KEY(PRODUCT_ID, SUPPLIER_ID)    ,
  FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCT(ID),
  FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIER(ID));