DROP TABLE IF EXISTS PRODUCT_SUPPLIER;

DROP TABLE IF EXISTS DISCOUNT;

DROP TABLE IF EXISTS PRODUCT;

DROP TABLE IF EXISTS PRODUCT_DICTIONARY;

DROP TABLE IF EXISTS MARKET_USER;

DROP TABLE IF EXISTS SUPPLIER;