CREATE TABLE SUPPLIER (
  ID INTEGER  NOT NULL   IDENTITY ,
  NAME VARCHAR(256)  NOT NULL  ,
  SHIPPING_DAYS INTEGER  NOT NULL    ,
PRIMARY KEY(ID));
GO




CREATE TABLE PRODUCT (
  ID INTEGER  NOT NULL   IDENTITY ,
  CODE VARCHAR(32)  NOT NULL    ,
  IMAGE BLOB   ,
PRIMARY KEY(ID)  );
GO


CREATE INDEX PRODUCT_CODE_IDX ON PRODUCT (CODE);
GO




CREATE TABLE MARKET_USER (
  ID INTEGER  NOT NULL   IDENTITY ,
  MAIL VARCHAR(100)  NOT NULL  ,
  PASSWORD VARCHAR(256)  NOT NULL  ,
  NAME VARCHAR(50)  NOT NULL  ,
  SURNAME VARCHAR(50)  NOT NULL  ,
  LANGUAGE CHAR(2)  NOT NULL    ,
PRIMARY KEY(ID)  );
GO


CREATE INDEX MAIL ON USER (MAIL);
GO




CREATE TABLE DISCOUNT (
  ID INTEGER  NOT NULL   IDENTITY ,
  SUPPLIER_ID INTEGER  NOT NULL  ,
  DATE_FROM DATE  NOT NULL  ,
  DATE_TO DATE  NOT NULL  ,
  PRICE_RANGE_FROM NUMERIC(10,2)    ,
  PRICE_RANGE_TO NUMERIC(10,2)    ,
  MIN_PIECE_DISCOUNT INTEGER      ,
PRIMARY KEY(ID)  ,
  FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIER(ID));
GO


CREATE INDEX DISCOUNT_FKIndex1 ON DISCOUNT (SUPPLIER_ID);
GO


CREATE INDEX IFK_Rel_02 ON DISCOUNT (SUPPLIER_ID);
GO


CREATE TABLE PRODUCT_DICTIONARY (
  ID INTEGER  NOT NULL   IDENTITY ,
  PRODUCT_ID INTEGER  NOT NULL  ,
  NAME VARCHAR(256)  NOT NULL  ,
  DESCRIPTION VARCHAR(2048)    ,
  LANGUAGE CHAR(2)  NOT NULL    ,
PRIMARY KEY(ID)    ,
  FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCT(ID),
UNIQUE KEY `PRODUCT_DICTIONARY_NATURAL_KEY` (`PRODUCT_ID`,`LANGUAGE`));
GO


CREATE INDEX PRODUCT_DICTIONARY_FKIndex1 ON PRODUCT_DICTIONARY (PRODUCT_ID);
GO
CREATE UNIQUE INDEX PRODUCT_DICTIONARY_index1252 ON PRODUCT_DICTIONARY (PRODUCT_ID, LANGUAGE);
GO


CREATE INDEX IFK_Rel_05 ON PRODUCT_DICTIONARY (PRODUCT_ID);
GO


CREATE TABLE PRODUCT_SUPPLIER (
  PRODUCT_ID INTEGER  NOT NULL  ,
  SUPPLIER_ID INTEGER  NOT NULL  ,
  PRICE NUMERIC(10,2)  NOT NULL  ,
  AVAILABILITY INTEGER  NOT NULL    ,
PRIMARY KEY(PRODUCT_ID, SUPPLIER_ID)    ,
  FOREIGN KEY(PRODUCT_ID)
    REFERENCES PRODUCT(ID),
  FOREIGN KEY(SUPPLIER_ID)
    REFERENCES SUPPLIER(ID));
GO


CREATE INDEX PRODUCT_has_SUPPLIER_FKIndex1 ON PRODUCT_SUPPLIER (PRODUCT_ID);
GO
CREATE INDEX PRODUCT_has_SUPPLIER_FKIndex2 ON PRODUCT_SUPPLIER (SUPPLIER_ID);
GO


CREATE INDEX IFK_Rel_03 ON PRODUCT_SUPPLIER (PRODUCT_ID);
GO
CREATE INDEX IFK_Rel_04 ON PRODUCT_SUPPLIER (SUPPLIER_ID);
GO


